# Start with the golang v1.16 image
FROM golang:1.16

# Setting environment variables for Go
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 
    # GOPRIVATE=github.com/pip-services3-go/*

# Copy local ssh keys
COPY docker/id_rsa /root/.ssh/

# Setup ssh access to git repositories
RUN chmod 600 /root/.ssh/id_rsa* \
    && ssh-keyscan github.com >> ~/.ssh/known_hosts \
    && ssh-keyscan gitlab.com >> ~/.ssh/known_hosts \
    && git config --global --add url."git@github.com:".insteadOf "https://github.com/"

# Set a working directory
WORKDIR /app

# Copy the entire project
COPY . .

# Install all go_modules
RUN go mod tidy
RUN go mod download

# Specify the command from running tests
CMD go clean -testcache && go test -v ./test/...
