FROM node:8

# Install development tools
RUN npm install typescript -g

# set working directory
WORKDIR /app
# copy project file
COPY package.json .
 
# install ALL node_modules, including 'devDependencies'
RUN npm install

# copy all project
COPY . .

# compile source code
RUN tsc
