FROM golang:1.16

# Set environment variables for Go
ENV GO111MODULE=on

WORKDIR /app

RUN go install golang.org/x/tools/cmd/godoc

WORKDIR /app

COPY . ./src

ENTRYPOINT godoc -http=0.0.0.0:6060 -v -goroot=. 