FROM golang:1.16

# Set environment variables for Go
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Set a working directory
WORKDIR /app

# Copy the package files
COPY . .

# Install all go_modules
RUN go mod tidy

# Build the project
RUN go build -o /app/main_service /app/bin/lambda/service/main.go 
RUN go build -o /app/main_container /app/bin/lambda/container/main.go
